# This is a basic workflow to help you get started with Actions

name: My first workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "my-first-job"
  my-first-job:
    name: My first job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      response: ${{ steps.print.outputs.response }}

    # Steps represent a sequence of tasks that will be executed as part of the job          
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Print
        id: print
        env:
          MY_VAL: Hello world
        run: echo "::set-output name=response::${MY_VAL}"
        
  my-second-job:
    needs: my-first-job
    name: My second job
    runs-on: ubuntu-latest
    steps:
      - name: Print
        id: print
        run: echo ${{needs.my-first-job.outputs.response}}
